[package]
name = "Ss58format-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
blake2 = "0.10.2"
base58 = "0.2.0"